name: badsound_counter_app
description: Find And Punish your friend's bad words!
version: 0.0.1+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  intl:
  retrofit: '>=4.0.0 <5.0.0'
  sentry_flutter: ^7.7.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.8.3
  get: ^4.6.5
  injectable:
  get_it:
  json_annotation:
  shared_preferences:
  webview_javascript_bridge:
  webview_flutter:
  quiver:
  cupertino_icons: ^1.0.2
  http:
  sign_in_with_apple: ^4.3.0
  firebase_messaging: ^14.6.3
  firebase_core: ^2.14.0
  flutter_local_notifications: ^14.1.1
  google_sign_in: ^6.1.4
  device_info: ^2.0.3
  sqflite: ^2.2.8+4
  image_picker: ^0.8.9
  cached_network_image: ^3.2.3
  rsocket: ^1.0.0
  toggle_switch: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator:
  retrofit_generator: '>=5.0.0 <6.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable:

flutter:
  uses-material-design: true
  assets:
    - assets/images/sign_in_with_apple_4x.png
    - assets/images/sign_in_with_google_4x.png
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-Regular.ttf
        - asset: assets/fonts/Pretendard/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard/Pretendard-Thin.ttf
          weight: 100
